#!/usr/bin/env python3
"""
Render Assignment 1 report tables from CSV -> LaTeX (.tex) with sane formatting. Help[er script

Why:
- CSVs are great for reproducibility and auditing.
- LaTeX tables are great for presentation.
- Generating .tex avoids manual formatting drift and prevents "squished" tables.

Assumptions:
- ran 09_report_tables_assignment1.sql and exported CSVs into outputs/tables/.
- main.tex lives in reports/assignment_1/, so we write tables into reports/assignment_1/tables/.

Output:
- reports/assignment_1/tables/*.tex files with booktabs + tabular/tabularx.

Assignement rendered in Overleaf but this makes inserting tables copy pasteable

"""

from __future__ import annotations
from pathlib import Path
import pandas as pd

IN_DIR = Path("outputs/tables")
OUT_DIR = Path("reports/assignment_1/tables")

def fmt_int_commas(x):
    if pd.isna(x): return ""
    return f"{int(x):,}"

def fmt_float(x, nd=2):
    if pd.isna(x): return ""
    return f"{float(x):.{nd}f}"

def write_table(tex: str, out_path: Path):
    out_path.write_text(tex, encoding="utf-8")
    print(f"Wrote {out_path}")

def table_wrap(df: pd.DataFrame, caption: str, label: str, tabular: str) -> str:
    # Use \small and tighter spacing inside tables (common in academic writing).
    return f"""% AUTO-GENERATED FILE. Do not edit by hand.
% Source: {IN_DIR}
\\begin{{table}}[H]
\\centering
\\small
\\setlength{{\\tabcolsep}}{{4pt}}
\\renewcommand{{\\arraystretch}}{{1.05}}
{tabular}
\\caption{{{caption}}}
\\label{{{label}}}
\\end{{table}}
"""

def to_tabular(df: pd.DataFrame, colspec: str) -> str:
    body = df.to_latex(
        index=False,
        escape=True,
        column_format=colspec,
        longtable=False,
        caption=False,
        label=False,
        bold_rows=False
    )
    # Pandas emits a full table env; strip to just tabular to embed in our wrapper.
    lines = body.splitlines()
    keep = []
    in_tab = False
    for ln in lines:
        if ln.startswith("\\begin{tabular"):
            in_tab = True
        if in_tab:
            keep.append(ln)
        if ln.startswith("\\end{tabular"):
            break
    # Replace default hlines with booktabs already used by pandas when booktabs=True;
    # but pandas uses \\toprule etc automatically if booktabs option set. We'll just
    # ensure it exists by replacing \hline patterns if any (rare).
    return "\n".join(keep)

def to_tabularx(df: pd.DataFrame, colspec: str) -> str:
    # tabularx needs explicit environment
    latex = df.to_latex(index=False, escape=True, header=True)
    # Extract rows (skip begin/end generated by pandas)
    rows = []
    for ln in latex.splitlines():
        if ln.startswith("\\begin{tabular"):
            continue
        if ln.startswith("\\end{tabular"):
            continue
        rows.append(ln)
    inner = "\n".join(rows).strip()
    return f"""\\begin{{tabularx}}{{\\textwidth}}{{{colspec}}}
{inner}
\\end{{tabularx}}"""

def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # 1) Table inventory
    inv = pd.read_csv(IN_DIR / "report_table_inventory_v1.csv")
    inv = inv.rename(columns={"table_name": "Table", "approx_rows": "Approx. rows"})
    inv["Approx. rows"] = inv["Approx. rows"].map(fmt_int_commas)
    tab = to_tabular(inv, colspec="l r")
    write_table(table_wrap(tab, "Table inventory (approximate row counts; demo extract).", "tab:table_inventory", tab),
                OUT_DIR / "report_table_inventory_v1.tex")

    # 2) Key integrity
    ki = pd.read_csv(IN_DIR / "report_key_integrity_v1.csv")
    ki = ki.rename(columns={"check_name": "Join path check", "n_orphans": "Orphans"})
    ki["Orphans"] = ki["Orphans"].map(fmt_int_commas)
    tab = to_tabularx(ki, colspec="X r")
    write_table(table_wrap(tab, "Key integrity checks (orphan counts on core join paths).", "tab:key_integrity", tab),
                OUT_DIR / "report_key_integrity_v1.tex")

    # 3) Vitals coverage
    vc = pd.read_csv(IN_DIR / "report_vitals_coverage_v1.csv")
    vc = vc.rename(columns={
        "var": "Vital",
        "n_stays": "N (stays)",
        "n_with_6h": "N w/ 6h",
        "pct_with_6h": "% w/ 6h",
        "n_with_24h": "N w/ 24h",
        "pct_with_24h": "% w/ 24h",
    })
    # formatting
    for c in ["N (stays)", "N w/ 6h", "N w/ 24h"]:
        vc[c] = vc[c].map(fmt_int_commas)
    for c in ["% w/ 6h", "% w/ 24h"]:
        vc[c] = vc[c].map(lambda x: fmt_float(x, 1))
    tab = to_tabular(vc, colspec="l r r r r r")
    write_table(table_wrap(tab, "Early-window vitals coverage (presence within 6h and 24h of ICU admission).", "tab:vitals_coverage", tab),
                OUT_DIR / "report_vitals_coverage_v1.tex")

    # 4) first_careunit counts
    cu = pd.read_csv(IN_DIR / "report_first_careunit_counts_v1.csv")
    cu = cu.rename(columns={"first_careunit": "First careunit", "n_stays": "N (stays)"})
    cu["N (stays)"] = cu["N (stays)"].map(fmt_int_commas)
    tab = to_tabularx(cu, colspec="X r")
    write_table(table_wrap(tab, "ICU stay distribution by first careunit (fragmentation check).", "tab:careunit_counts", tab),
                OUT_DIR / "report_first_careunit_counts_v1.tex")

    # 5) outcome prevalence
    op = pd.read_csv(IN_DIR / "report_outcome_prevalence_v1.csv")
    op = op.rename(columns={
        "n_stays": "N (stays)",
        "n_prolonged_8d": "N prolonged (≥8d)",
        "pct_prolonged_8d": "% prolonged (≥8d)",
    })
    op["N (stays)"] = op["N (stays)"].map(fmt_int_commas)
    op["N prolonged (≥8d)"] = op["N prolonged (≥8d)"].map(fmt_int_commas)
    op["% prolonged (≥8d)"] = op["% prolonged (≥8d)"].map(lambda x: fmt_float(x, 1))
    tab = to_tabular(op, colspec="r r r")
    write_table(table_wrap(tab, "Outcome prevalence for prolonged ICU length of stay (LOS ≥ 8 days).", "tab:outcome_prevalence", tab),
                OUT_DIR / "report_outcome_prevalence_v1.tex")

    # 6) LOS summary
    ls = pd.read_csv(IN_DIR / "report_los_summary_v1.csv")
    ls = ls.rename(columns={
        "n_stays": "N",
        "los_min_days": "Min",
        "los_p25_days": "P25",
        "los_median_days": "Median",
        "los_p75_days": "P75",
        "los_max_days": "Max",
        "los_mean_days": "Mean",
    })
    ls["N"] = ls["N"].map(fmt_int_commas)
    for c in ["Min", "P25", "Median", "P75", "Max", "Mean"]:
        ls[c] = ls[c].map(lambda x: fmt_float(x, 2))
    tab = to_tabular(ls, colspec="r r r r r r r")
    write_table(table_wrap(tab, "ICU length-of-stay (days) summary statistics.", "tab:los_summary", tab),
                OUT_DIR / "report_los_summary_v1.tex")

if __name__ == "__main__":
    main()
